#!/bin/bash


##########################################
##########################################
# Configuration globale du profile GITHUB
git config --global user.name "HamzaMoinet"
git config --global user.email "moinethamza0@gmail.com"

# Exemple de clonage d'une repo GITHUB avec le TOKEN dans le URL pour éviter la saisie des coordonnées à chaque git push
# Replacer YOUR_GITHUB_USERNAME, YOUR_PERSONAL_ACCESS_TOKEN, et REPO_URL avec vos vraies informations.

git clone https://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@github.com/HamzaMoinet/holbertonschool-low_level_programming.git



##########################################
##########################################
# Configuration de EMACS
cd $HOME
touch .emacs

cat > .emacs << 'EOF'
(setq c-default-style "bsd"
      c-basic-offset 8
      tab-width 8
      indent-tabs-mode t)

(require 'whitespace)
(setq whitespace-style '(face empty lines-tail trailing))
(global-whitespace-mode t)

(setq column-number-mode t)
EOF


##########################################
##########################################
# Configuration de VIM

cd $HOME
touch .vimrc

cat > .vimrc << 'EOF'
set tabstop=8 shiftwidth=8
set autoindent
set smartindent
set cindent
syntax enable
set number
EOF
